[debug]
address = "0.0.0.0"
port = 8000

desk_server_ip = "192.168.0.69"
fava_base = "http://localhost:5000/"
beancount_location = "main.bean"

[default]
oauth_base = "https://oauth.nicky.gent"
# client_id = "only-scan"
# client_secret= "Y5xSinM49kNIsw3Tcn02pTXYHO2YED9zRqJTJukzwMGp68lajc34kArNSHPzcWHq"
client_id = "only_scan_dev"
client_secret = "eZfWuC9BmGHYFxfylJWCWDSQDwWRl0cLa5B01TATbCcIgz3OKXBIpROuuDgp2Yof"

[default.limits]
file = "20 MiB"
forms = "20 Mib"

