[debug]
address = "0.0.0.0"
port = 8000

desk_server_ip = "192.168.0.69"
beancount_location = "test.bean"

[default]
database_url = "postgres://onlyscan:password@localhost/diesel_demo"
oauth_base = "http://localhost:8001" 
client_id = "only-scan"
client_secret= "Y5xSinM49kNIsw3Tcn02pTXYHO2YED9zRqJTJukzwMGp68lajc34kArNSHPzcWHq"



[default.limits]
file = "20 MiB"
forms = "20 Mib"
